XPATH_LASTPAGE_NUMBER = '(//li[contains(@class, "page")])[last()]/a/@href'
XPATH_URLS = '//div[contains(@class, "goods-card__name")]/a/@href'
XPATH_PRICES = '//span[contains(@class, "cost")]/text()'
XPATH_STOCK = '//div[contains(@class, "not-available")]/text()'
XPATH_DESCRIPTION = '//div[@itemprop="description"]'
XPATH_IMAGE = '//div[contains(@class, "picture")]/img/@src'
XPATH_BRAND = '//span[@itemtype="legalName"]/text()'
XPATH_COUNTRY = '//span[@itemtype="location"]/text()'
XPATH_TITLE = '//h1/span[@itemprop="name"]/text()'
XPATH_RPC = '//div/@data-product-id'
XPATH_SECTION = '//span[@class="ui-link__text"]/span[@itemprop="name"]/text()'
XPATH_METADATA = '//div[@itemprop="description"]/*'
XPATH_MARKETING_TAG = '//span[contains(@class, "tag")]/text()'

